name: Any Branch Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    
    - name: Build
      run: |
        echo "Building on branch: ${{ github.ref_name }}"
        echo "Event: ${{ github.event_name }}"
        
        go mod download
        go build -o nexus-util .
        
        if [ -f "nexus-util" ]; then
          echo "✅ Build successful!"
          ls -la nexus-util
        else
          echo "❌ Build failed!"
          exit 1
        fi