name: Test Workflow

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Test step
      run: |
        echo "Hello from GitHub Actions!"
        echo "Branch: ${{ github.ref_name }}"
        echo "Event: ${{ github.event_name }}"
        echo "Repository: ${{ github.repository }}"
        echo "Workflow: ${{ github.workflow }}"
        
        # List files
        echo "Files in repository:"
        ls -la
        
        # Check if Go files exist
        if [ -f "main.go" ]; then
          echo "✅ main.go found"
        else
          echo "❌ main.go not found"
        fi